name: Build library

on:
  push:
    branches:
      - master
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/umroboticsteam/umrt-build:testing-docker-build

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: ./src
          submodules: 'true'

      - name: Prepare to build debian
        working-directory: ./src
        run: |
          . /opt/ros/humble/setup.sh
          rosdep update
          bloom-generate rosdebian

      - name: Build debian
        working-directory: ./src
        run: fakeroot debian/rules binary

      - name: Pass deb to publishing container
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: "*.deb"

  publish:
    needs: build

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/umroboticsteam/umrt-apt-image:initial-setup

    steps:
      - name: Download deb
        uses: actions/download-artifact@v4
        with:
          name: deb
          path: ./deb

      - name: Delete deb artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: deb

      - name: Load signing and deploy keys
        working-directory: .
        run: |
          echo -n "$APT_SIGNING_KEY" | gpg --import
        env:
          APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}

      - name: Checkout apt repo
        uses: actions/checkout@v4
        with:
          repository: 'UMRoboticsTeam/umrt-apt-repo'
          path: ./apt
          ref: 'testing-ci-cd'
          # Note that this is persisted in the local Git config until the post-job task
          persist-credentials: true
          ssh-key: {{ secrets.APT_DEPLOY_KEY }}

      - name: Publish debians
        working-directory: ./apt
        run: reprepro --section arm --component main --priority 0 includedeb humble ../deb/*

      - name: Push apt repo
        working-directory: ./apt
        run: |
          git config --global user.name 'UMRT Build Server'
          git config --global user.email 'umrt.exec@gmail.com'
          git add --all
          git commit -S -m "Uploaded new version of ${{ github.repository }}"
          git push origin
